version: "3.8"

services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      app_network:
        aliases:
          - nginx
    volumes:
      - .:/app
      - ./config/nginx/stack.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/certs/ca.crt:/etc/ssl/air-project.xyz/ca.crt
      - ./config/nginx/certs/air-project.crt:/etc/ssl/air-project.xyz/air-project.crt
      - ./config/nginx/certs/air-project.key:/etc/ssl/air-project.xyz/air-project.key
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    healthcheck:
      start_period: 180s
      test: curl --fail -s ${PROJECT_FULL_DOMAIN}/ || exit 1

  db:
    image: postgres:11.13-alpine
    env_file:
      - ${ENV}
    environment:
      - POSTGRES_USER=${POSTGRES_PROD_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PROD_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PROD_DB}
    networks:
      - app_network
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data/
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        constraints: [ node.role == manager ]
    healthcheck:
      start_period: 60s
      test: pg_isready -U ${POSTGRES_DEFAULT_USER} -d ${POSTGRES_DB}

  redis:
    image: redis:6.2.6-alpine
    env_file:
      - ${ENV}
    ports:
      - "6380:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints: [ node.role == manager ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  daphne:
    image: romanreznikov/backend:${CI_COMMIT_SHORT_SHA}
    env_file:
      - ${ENV}
    command: >
      bash -c "cd /app/airbnb_app/
      && daphne -b 0.0.0.0 -p 8001 airbnb.asgi:application"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      app_network:
        aliases:
          - daphne
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    healthcheck:
      start_period: 60s
      interval: 10s
      retries: 10
      test: curl --fail -s ${PROJECT_FULL_DOMAIN}/realty/ || exit 1

  server:
    image: romanreznikov/backend:${CI_COMMIT_SHORT_SHA}
    env_file:
      - ${ENV}
    environment:
      - DEBUG=0
      - ENVIRONMENT=prod
      - DJANGO_SETTINGS_MODULE=airbnb.settings.pro
    command: >
      bash -c "cd /app/airbnb_app/
      && python manage.py migrate --noinput
      && python manage.py collectstatic --no-input
      && gunicorn -c /app/config/gunicorn_config.py airbnb.wsgi"
    depends_on:
      - db
      - redis
    networks:
        app_network:
          aliases:
            - server
    volumes:
      - .:/app
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    healthcheck:
      start_period: 60s
      interval: 10s
      retries: 10
      test: curl --fail -s ${PROJECT_FULL_DOMAIN}/api/v1/realty/ || exit 1

  celery:
    image: romanreznikov/backend:${CI_COMMIT_SHORT_SHA}
    env_file:
      - ${ENV}
    command: >
      bash -c "cd /app/airbnb_app/
      && celery -A airbnb worker -l info"
    depends_on:
      - redis
      - db
      - server
    networks:
      - app_network
    volumes:
      - .:/app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: pause
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 3
      test: cd airbnb_app/ && celery -A airbnb inspect ping || exit 1

  flower:
    image: mher/flower:0.9.5
    env_file:
      - ${ENV}
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=${FLOWER_PORT}
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery
    networks:
        app_network:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  celery_beat:
    image: romanreznikov/backend:${CI_COMMIT_SHORT_SHA}
    env_file:
      - ${ENV}
    command: >
      bash -c "cd /app/airbnb_app/
      && celery -A airbnb beat -l info --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - db
      - server
      - celery
    networks:
      - app_network
    volumes:
      - .:/app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 5
      test: cd airbnb_app/ && celery -A airbnb inspect ping || exit 1

networks:
  app_network:

volumes:
  postgres_data:
  redis_data:
