version: "3.8"
services:
  redis:
    image: redis

  airbnb:
    build: .
    volumes:
      - .:/airbnb-docker
    ports:
      - 8000:8000
    image: web:airbnb-app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: airbnb_app
