version: "3.8"

services:
  redis:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
    image: redis
    ports:
      - 6380:6379
    container_name: ${AIRBNB_REDIS_HOST}

  celery:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    restart: always
    build: .
    command: celery -A airbnb worker -l info
    volumes:
      - .:/airbnb-docker
    links:
      - redis
    depends_on:
      - redis
      - web

  flower:
    env_file:
      - .env
    environment:
      - CELERY_BROKER_TRANSPORT=redis
      - CELERY_BROKER_HOST=redis
      - CELERY_BROKER_PORT=6379
      - CELERY_BROKER_VHOST=2
      - CELERY_REDIS_DB=2
      - CELERY_BROKER_URL=${CELERY_BROKER_HOST}://${CELERY_BROKER_TRANSPORT}:${CELERY_BROKER_PORT}/${CELERY_REDIS_DB}
      - FLOWER_PORT=5555
    image: mher/flower
    volumes:
      - .:/airbnb-docker
    restart: always
    command: flower --broker=${CELERY_BROKER_URL}
    ports:
      - 5555:5555
    container_name: airbnb_flower
    depends_on:
      - celery
      - redis

  celery_beat:
    env_file:
      - .env
    environment:
      - CELERY_BROKER_TRANSPORT=redis
      - CELERY_BROKER_HOST=redis
      - CELERY_BROKER_PORT=6379
      - CELERY_BROKER_VHOST=2
      - CELERY_REDIS_DB=2
      - CELERY_BROKER_URL=${CELERY_BROKER_HOST}://${CELERY_BROKER_TRANSPORT}:${CELERY_BROKER_PORT}/${CELERY_REDIS_DB}
      - FLOWER_PORT=5555
    build: .
    restart: on-failure
    volumes:
    - .:/airbnb-docker
    command: celery -A airbnb beat -l info --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler
    container_name: airbnb_celery_beat
    depends_on:
      - redis
      - web

  daphne:
    restart: always
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
      - CELERY_BROKER_TRANSPORT=redis
      - CELERY_BROKER_HOST=redis
      - CELERY_BROKER_PORT=6379
      - CELERY_BROKER_VHOST=2
      - CELERY_REDIS_DB=2
      - REDIS_URL=${CELERY_BROKER_HOST}://${CELERY_BROKER_TRANSPORT}:${CELERY_BROKER_PORT}/${CELERY_REDIS_DB}
    build: .
    volumes:
      - .:/airbnb-docker
    ports:
      - 8000:8000
    command: daphne -b 0.0.0.0 -p 8000 airbnb.asgi:application
    depends_on:
      - redis

  web:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
      - CELERY_BROKER_TRANSPORT=redis
      - CELERY_BROKER_HOST=redis
      - CELERY_BROKER_PORT=6379
      - CELERY_BROKER_VHOST=2
      - CELERY_REDIS_DB=2
      - REDIS_URL=${CELERY_BROKER_HOST}://${CELERY_BROKER_TRANSPORT}:${CELERY_BROKER_PORT}/${CELERY_REDIS_DB}
    build: .
    volumes:
      - .:/airbnb-docker
    image: web:airbnb-app
    # TODO: configure nginx to run standard HTTP requests through a WSGI server (another milestone)
    command: python manage.py runworker --settings airbnb.settings channels airbnb.asgi:application
    container_name: airbnb_app
