version: "3.8"
services:
  redis:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
    image: redis
    ports:
      - 6380:6379
    container_name: ${AIRBNB_REDIS_HOST}

  celery:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
    restart: always
    build: .
    command: celery -A airbnb worker -l info
    volumes:
      - .:/airbnb-docker
    links:
      - redis
    depends_on:
      - redis
      - airbnb

  flower:
    env_file:
      - .env
    environment:
      - CELERY_BROKER_TRANSPORT=redis
      - CELERY_BROKER_HOST=redis
      - CELERY_BROKER_PORT=6379
      - CELERY_BROKER_VHOST=2
      - CELERY_REDIS_DB=2
      - CELERY_BROKER_URL=${CELERY_BROKER_HOST}://${CELERY_BROKER_TRANSPORT}:${CELERY_BROKER_PORT}/${CELERY_REDIS_DB}
      - FLOWER_PORT=5555
    image: mher/flower
    volumes:
      - .:/airbnb-docker
    restart: always
    command: flower --broker=${CELERY_BROKER_URL}
    ports:
      - 5555:5555
    container_name: airbnb_flower
    depends_on:
      - celery
      - redis


  airbnb:
    env_file:
      - .env
    environment:
      - AIRBNB_REDIS_HOST=airbnb_redis
    build: .
    volumes:
      - .:/airbnb-docker
    ports:
      - 8000:8000
    image: web:airbnb-app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: airbnb_app
